var resume = {
    contact: {
        name: {
            firstNameF: "Abdelkareem",
            firstNameS: "Kareem",
            lastName: "Jaradat",
        },
        address: { 
            apartment: "709",
            street: "Kipps Lane",
            city: "London ON",
            country: "Canada",
            postalCode: "N5Y4Y1",
        },
        mobile: "+1-226-998-4341",
        email: "kareem.jaradat@algomau.ca",
        website: "Jaradat.ca",
        linkedin: "linkedin.com/in/abedjar",
        objective: "Through the past 14 years, I have gained an enormous amount of experience in the web design and development during serving in multiple roles among various institutions around the world. Most of the positions I have held involved web design as a major component. Tens of websites, web applications and portals I played as the leading designer in the development team. On the other hand, when I started my graduate studies at Western, I assisted in teaching web design courses in the majority of my time. I was assigned as the lead teaching assistant over years in these course. I helped hundreds of first and second year students to practically and theoretically understandi the web design and development using HTML/CSS both in in-person and over zoom course delivery. I strongly believe that I can bring a lot to this course since I have the skills and qualifications needed to successfully deliver such course.  ---------- I am a business analyst with experience of successful project delivery, particularly in the internal e-services industry as my latest two positions.I am adaptable, have a good understanding of commercial and business issues, a strong technical background, Problem-Solving, Critical Thinking, Visual Modeling and excellent communication skills. This allows me to fulfil a variety of different roles within project teams, and provide an effective interface between business and technical functions. ******** A highly focused software developer with 8 years’ experience in a variety of development and engineering positions. Organised, methodical and a keen eye for detail results in solid coding and trustworthy software programmes. I am adaptable, have a good understanding of commercial and business issues, a strong technical background in .Net, Problem-Solving, Critical Thinking, Visual Modelling and excellent communication skills. This allows me to fulfil a variety of different roles within project teams, and provide an effective interface between business and technical functions.",
    },
    education: [{
        date: "SEP 2019-Nov 2025",
        institute: "The University of Western Ontario (UWO)",
        department: "Computer Science",
        country: "Canada",
        degree: "PhD. in Computer Science",
        gpa: "98",
        level: "excellent",
    },
    {
        date: "SEP 2017-AUG 2019",
        institute: "The University of Western Ontario (UWO)",
        department: "Computer Science",
        country: "Canada",
        degree: "MSc. in Computer Science (thesis-based)",
        gpa: "95",
        level: "excellent",
    },
    {
        date: "SEP 2004-JUN 2009",
        institute: "Jordan University of Science and Technology (JUST)",
        department: "Computer Engineering",
        country: "Jordan",
        degree: "BSc. in Computer Engineering (with honors)",
        gpa: "88.3",
        level: "excellent",
        rank: "4/76",
    },
    {
        date: "SEP 2003-AUG 2004",
        institute: "Irbid Secondary School for Boys",
        department: "Science",
        country: "Jordan",
        degree: "General Certificate of Secondary Education (TAWJIHI)",
        gpa: "93.7",
        rank: "96.79%",
    },
    ],
    publications: [{
        title: "HYDROSAFE: A Hybrid Deterministic-Probabilistic Model for Synthetic Appliance Profiles Generation",
        author: "Jaradat, Abdelkareem and Alarbi, Muhamed and Lutfiyya, Hanan and Haque, Anwar",
        journal: "MDPI Sensors 24.17 (2024): 5619.",
        date: "2024"
    },{
        title: "SCOPE: Smart Cooperative Parking Environment",
        author: " Alarbi, Muhamed and Jaradat, Abdelkareem and Lutfiyya, Hanan and Haque, Anwar",
        journal: "IEEE Access 11: 120346-120361",
        date: "2023",
        organization: "IEEE",
        city: "Abu Dhabi",
        country: "UAE",
    },{
        title: "Smart Home Energy Visualizer: A Fusion of Data Analytics and Information Visualization",
        author: "Jaradat, Abdelkareem and Lutfiyya, Hanan and Haque, Anwar",
        journal: "IEEE Canadian Journal of Electrical and Computer Engineering",
        date: "2022",
        organization: "IEEE"
    },{
        title: "Synthetic Power Consumption Data Generation For Appliance Operation Modes",
        author: "Jaradat, Abdelkareem and Lutfiyya, Hanan and Haque, Anwar",
        journal: "2024 International Conference on Computing, Networking and Communications (ICNC)",
        date: "2024",
        organization: "IEEE",
        city: "Big Isalnd, Hawaii",
        country: "USA",
    },{
        title: "Appliances Operation Modes Identification Using States Clustering",
        author: "Jaradat, Abdelkareem and Alarbi, Muhamed and Lutfiyya, Hanan and Haque, Anwar",
        journal: "2023 International Conference on Smart Applications, Communications and Networking (SmartNets)",
        date: "2023",
        organization: "IEEE",
        city: "Istanbul",
        country: "Turkey",
    }, {
        title: "Density And Dynamic Time Warping Based Spatial Clustering For Appliance Operation Modes",
        author: "Jaradat, Abdelkareem and Lutfiyya, Hanan and Haque, Anwar",
        journal: "2023 IEEE PES Conference on Innovative Smart Grid Technologies - Middle East (ISGT Middle East)",
        date: "2023",
        organization: "IEEE"
    },
     {
        title: "Demand Response for Residential Uses: A Data Analytics Approach",
        author: "Jaradat, Abdelkareem and Lutfiyya, Hanan and Haque, Anwar",
        journal: "2020 IEEE 6th World Forum on Internet of Things (WF-IoT)",
        pages: "1-6",
        date: "2020",
        organization: "IEEE",
        city: "Luisiana",
        country: "USA",
    }
    ],
    talks: [{
        date: "July 2023",
        title: "Appliances Operation Modes Identification Using States Clustering",
        location: "Yeditepe University, Istanbul, Turkey.",
    }, {
        date: "March 2023",
        title: "Density And Dynamic Time Warping Based Spatial Clustering For Appliance Operation Modes",
        location: "Khalifa University, Abu Dhabi, UAE",
    }, {
        date: "June 2021",
        title: "TOWARDS SMART DEMAND RESPONSE: A COMPREHENSIVE SMART HOME ENERGY MANAGEMENT SYSTEM",
        location: "WING mothly meeting",
    },
    {
        date: "April 2021",
        title: "Smart Home Energy Visualizer",
        location: "UWORCS21",
    },
    {
        date: "June 2020",
        title: "Demand Response for Residential Uses: A Data Analytics Approach",
        location: "WF-IoT20",
    },
    {
        date: "Aug 2019",
        title: "CLASSIFYING APPLIANCES OPERATION MODES USING DYNAMIC TIME WARPING (DTW) AND K NEAREST NEIGHBORS (KNN)",
        location: "Master thesis defence",
    },
    {
        date: "Aug 2019",
        title: "A GLIMPSE ON CONSUMER BEHAVIOR CHANGE IN ELECTRIC POWER CONSUMPTION USING SOCIALIZED GAMIFICATION PLATFORM",
        location: "Reading course",
    },
    {
        date: "April 2019",
        title: "Applying Demand Response (DR) on Residential Houses Using XCorrelation And Dynamic Time Warping (DTW) On Disaggregated Appliance Power Consumption Data",
        location: "UWORCS 2019",
    },
    {
        date: "Nov 28, 2018",
        title: "Enhancing demand response by domestic electricity consumption by giving tips based on daily time series power consumption",
        location: "Industry Presentation for Tillsonburg Hydro Inc.",
    },
    ],
    awards: [{
        date: "APR 2021",
        name: "SmartNets23 Best paper award",
        reason: "Best paper award",
        url: "https://smartnets.ieee.tn/",
        institute: "IEEE",
    }, {
        date: "APR 2021",
        name: "UWORCS21 conference",
        reason: "Won first place prize",
        url: "https://www.csd.uwo.ca/conf/UWORCS/2019/results.html",
        institute: "Western University (UWO)",
    },
    {
        date: "2019-now",
        name: "Western Graduate Research Scholarship (WGRS)",
        reason: "completeing PhD degree in computer science",
        url: "https://grad.uwo.ca/current_students/student_finances/wgrs.html",
        institute: "Western University (UWO)",
    },
    {
        date: "APR 2019",
        name: "UWORCS2019 conference",
        reason: "Won first place prize",
        url: "https://www.csd.uwo.ca/conf/UWORCS/2019/results.html",
        institute: "Western University (UWO)",
    },
    {
        date: "2017-2019",
        name: "Western Graduate Research Scholarship (WGRS)",
        reason: "completeing MSc degree in computer science",
        url: "https://grad.uwo.ca/current_students/student_finances/wgrs.html",
        institute: "Western University (UWO)",
    },
    {
        date: "2007, 2008",
        name: "President's list of honors",
        reason: "Listed twice",
        institute: "Jordan University of Science and Technology (JUST)",
    },
    {
        date: "2004-2009",
        name: "Dean's list of honors",
        reason: "Listed eight times",
        institute: "Jordan University of Science and Technology (JUST)",
    },
    {
        date: "2006, 2007, 2008",
        name: "MHE Scholarship",
        reason: "Granted three times Awarded to the Engineering undergraduates with the highest overall GPA",
        institute: "Ministry of Higher Education (MHE)",
    },
    {
        date: "2006, 2007, 2008",
        name: "KAFD Scholarship",
        reason: "Granted three times Awarded to the Engineering undergraduates with the highest overall GPA",
        url: "http://www.just.edu.jo/Deanships/DeanshipofStudentsAffairs/Departments/KingAbdullahIIFundforDevelopment(KAFD)",
        institute: "King Abdullah'II Fund for Development (KAFD)",
    },
    {
        date: "2002",
        name: "Jordanian conference for High  Schools mathematics computing",
        reason: "Won first place prize",
        institute: "Ministry Of Education",
    },
    ],
    experience: [{
        date: "DEC 2025-Present",
        position: "Assiatant Professor",
        company: "Algoma University",
        city: "Brampton, ON",
        country: "Canada",
        mainDuty: "Full time faculty member.",
        dutiesF: [],
        duteisS: [],
    },{
        date: "SEP 2022-AUG 2024",
        position: "Sessional Instructor",
        company: "Western University (UWO)",
        city: "London, ON",
        country: "Canada",
        mainDuty: "Teaching, coordinating and managing programming courses at the department of computer science in both in-person and online delivery modes. Coordinating a team of instructors and teaching assistants of up to 20 members and classes of 1000+ students.",
        dutiesF: [],
        duteisS: [],
    },{
        date: "AUG 2024-Present",
        position: "Peer Consultant in Teaching and Learning",
        company: "Macmillan Learning",
        city: "Remote",
        country: "USA",
        mainDuty: "Provide support to worldwide instructors through  delivering in-person or virtual presentations, conducting faculty trainings, offering consultations via email, phone, or Zoom,  creating content such as blog posts, whitepapers, or videos, and contributing to product development by participating in beta tests and offering feedback.",
        dutiesF: [],
        duteisS: [],
    },
                 {
        date: "SEP 2017-Present",
        position: "Graduate Teaching and Research Assistant",
        company: "Western University (UWO)",
        city: "London, ON",
        country: "Canada",
        mainDuty: "Working on a research topic related to reducing energy consumption by changing consumers behaviours in different approaches like Bloom's Taxonomy, data analytics, machine learning and Visualization.",
        dutiesF: [
            "Fundamentals of computer science using Python (in person and online)"
            , "Object-Oriented Design and Analysis "
            , "Computer Science Fundamentals II "
            , "Multimedia and communication II"
            , "Multimedia and communication I"
            , "Software Tools and System Programming"
        ],
        duteisS: [],
    },
    {
        date: "OCT 2015-FEB 2017",
        position: "Business Systems Analyst",
        company: "Saudi Ministry of defense/EJADA Systems",
        city: "Riyadh",
        country: "Saudi Arabia",
        mainDuty: "",
        dutiesF: [
            "Requirement elicitation using combinations of techniques like brainstorming, document analysis, existed interface analysis, Interviews and prototyping",
            "Create and documented process descriptions, SRS documents and process flows as well as robust use cases",
            "Strategic development of business solutions",
            "Meet clients to gather their stories about what they want and evaluate, document functional business requirements",
            "Produce visual workflows, UML diagrams, slide presentations and infographic content to help underlying layers to digest ideas and understand the needs clearly",
            "Design live prototypes at the early stages of project with the latest web design libraries",
            "Participating in analyzing, building and UI/UX enhancing for web applications based on state of the art technologies; Asp.net MVC/WEB API , jQuery/AJAX and bootstrap/css3",
        ],
        duteisS: [],
    },
    {
        date: "MAR 2015-OCT 2015",
        position: "Senior .Net Web Developer",
        company: "Saudi Ministry of defense/EJADA Systems",
        city: "Riyadh",
        country: "Saudi Arabia",
        mainDuty: "",
        dutiesF: [
            "Analyzing, building and UI/UX enhancing for web applications based on state of the art technologies; Asp.net MVC/WEB API , jQuery/AJAX and bootstrap/css3",
            "Develop/Design a simple and effective reporting methodology using only Html/css",
            "Architect a generic ORM-like framework that lays on the data access layer",
            "Develop code generation tools to fasten adopted code implementation process",
            "Analyze new/existing database systems through producing SRS documents",
            "Design live prototypes at the early stages of project with the latest web design libraries",
            "Design art works, print materials, web banners, mockups and vector using Adobe apps",
        ],
        duteisS: [],
    },
    {
        date: "FEB 2010-MAR 2015",
        position: "Full stack developer",
        company: "Jordan University of Science and Technology (JUST)",
        city: "Irbid",
        country: "Jordan",
        mainDuty: "",
        dutiesF: [
            "Full-Stack business process in analyzing and building web application",
            "Focusing on early stages of SDLC; meeting clients to gather business needs",
            "Visualize business requirements into wireframes, mockups and demos with full functionalities",
            "Building web application using Asp.net/C# & web graphics",
        ],
        duteisS: [],
    },
    {
        date: "2009-present",
        position: "Web Developer/Graphic Designer",
        company: "Freelancer",
        city: "-",
        country: "Jordan, KSA, Australia, Germany, Qatar, Canada and UAE",
        mainDuty: "Working on the whole SDLC stack for various projects",
        dutiesF: [],
        duteisS: [],
    },
    {
        date: "JAN 2013-JUN 2013",
        position: "Course instructor",
        company: "Integrated Horizons for Training (IHT)",
        city: "Irbid",
        country: "Jordan",
        mainDuty: "Responsible for training and supervising undergraduate IT student in completing their graduation projects in Asp.net, C#, VB.net, SQL server and MS Access.",
        dutiesF: [],
        duteisS: [],
    },
    {
        date: "AUG 2009-JAN 2010",
        position: "GUI & Software Development Engineer",
        company: "CIAPPLE",
        city: "Amman",
        country: "Jordan",
        mainDuty: "Responsible for building computational intelligence web application for DB clustering",
        dutiesF: [],
        duteisS: [],
    },
    {
        date: "Feb 2009-AUG 2009",
        position: "Software Development Engineer",
        company: "Systems and Electronic Development Co (SEDCO)",
        city: "Amman",
        country: "Jordan",
        mainDuty: "Responsible for building many windows applications under VB.Net and integrate them with an existing applications.",
        dutiesF: [
            "XML Reader windows service & Flash 8 movie that reads News, weather and Prays Times from Webserver and distributed to display LCDs",
            "Building a Windows CE 6.0 image using Platform Builder 6 to use it to operate a  800 VESA Compact pc in many banks branches for queuing purposes.",
            "Packaging several installation files into one universal self-installer with customized GUI.",
            "Developing a file transfer/Chat Application using .NET Remoting & Windows Sockets to communicate between VESA Compact PCs and Administration PCs.",
            "Full customization and enhancements for an open source survey application built with PHP, Javascript, CSS and MS SQL Server 2005 deployed on a stand KIOSK for customers feedback.	",
        ],
        duteisS: [],
    },
    {
        date: "OCT 2007-JUN 2008",
        position: "Graphic Designer Intern",
        company: "Jordan University of Science and Technology (JUST) Students Affairs",
        city: "Irbid",
        country: "Jordan",
        mainDuty: "Design official documents, advertisements, Brochures and flyers",
        dutiesF: [],
        duteisS: [],
    },
    ],
    skills: {
        core: [
            "Broad development knowledge for back-end, front-end and database, including C#, ASP.Net, MVC, WebAPI, SQL server and oracle databases, HTML5, CSS3, Bootstrap, Responsive Web, JavaScript and jQuery",
            "Industry aware and technically up to speed with current software development tools, including Visual Studio 2015, and MS TFS",
            "Strong analytical skills and level headed problem solver with very high communication skills like team management, persuasion and arguing, critical Thinking, Interpersonal skills, Analytical and Team Working",
            "Strong and solid knowledge in both object orientated (OOP) and service oriented architecture (SOA) concepts and innovating / enhancing algorithms",
            "Expert in design concepts for both web applications and print materials using Adobe products",
        ],
        communication: [
            "Team Management, Persuasion and Arguing, Problem Solving, Critical Thinking, Interpersonal skills, Analytical and puzzle solver",
            "Motivated, Enthusiastic and a Team Worker",
        ],
        technical: [{
            name: "Web Development",
            skills: [
                "Asp.net MVC5",
                "Asp.net WebForms",
                "Asp.net WebPages",
                "Razor views",
                "HTML5",
                "WCF",
                "SignalR",
                "WebAPI",
                "PHP",
            ],
        },
        {
            name: "Web Design",
            skills: [
                "UX/UI",
                "CSS 3.0",
                "Bootstrap 3.x",
                "jQuery UI",
                "Responsive Web  Design",
                "LESS",
                "SASS",
                "CSS Animation",
                "animate.css",
                "Web charts",
                "FontAwesome",
                "Fontello",
                "HTMLkickstart",
                "",
            ],
        },
        {
            name: "Programming",
            skills: [
                "C#.Net",
                "VB.Net",
                "Data structures",
                "C++",
                "C",
                "Visual Basic",
                "Crystal Reports",
                "Action Script",
                "Python",
                "Android",
                "SimScript",
            ],
        },
        {
            name: "Scripting",
            skills: [
                "JavaScript",
                "jQuery",
                "AngularJs",
                "knockout",
                "AJAX",
                "DOM",
                "XML",
                "JSON",
                "handlebars",
                "Typescript",
                "TypeAhead",
                "Hogan",
                "Zepto",
                "holder.js",
                "slimscroll.js",
                "knockout",
                "AngularJs",
                "Jade",
            ],
        },
        {
            name: "Database",
            skills: [
                "DDL&DML Scripts",
                "MSSQL Server",
                "SQL Stored Procedures",
                "ADO.ApacheNET",
                "Entity Framework 6",
                "Linq",
                "Linq to SQL",
                "MySQL",
                "Oracle 10g",
                "MS Access",
                "PL/SQL",
                "Data mining",
            ],
        },
        {
            name: "Graphic Design & Animations",
            skills: [
                "Adobe Photoshop CC",
                "Adobe Illustrator CC",
                "Adobe InDesign CC",
                "Branding",
                "Print Design",
                "Adobe Flash CC",
                "Inkscape",
                "GDI+",
            ],
        },
        {
            name: "Software Engineering",
            skills: [
                "Project Planning",
                "n-tier programming",
                "Prototyping",
                "Technical Writing",
                "Requirements Analysis",
                "Waterfall",
                "Agile",
                "Iterative",
            ],
        },
        {
            name: "Software Tools and Packages",
            skills: [
                "Visual Studio 2013",
                "SQL Server Management Studio 2012",
                "Adobe Suite CC",
                "Microsoft Team Foundation Server TFS",
                "Toad for Oracle",
                "Sketchup",
                "Matlab 7",
                "MS Office Suite",
                "Quartus II",
                "Synapticad",
                "Pspice",
                "AutoCAD",
                "SimScript Simulation Studio",
                "Microsoft Visual C++ 6.0",
                "Rational Rose",
                "MS Visio",
                "MS FrontPage",
                "MS Platform Builder for Windows CE 6.0",
                "LimeSurvey",
                "Visual Source Safe",
                "Powershell",
                "Wordpress themes",
                "Fiddler",
                "XAMPP",
            ],
        },
        { name: "Web Servers", skills: ["IIS", "Apache"] },
        { name: "Assembly language", skills: ["MIPS R2000", "MOTROLA 68000"] },
        { name: "Hardware Description", skills: ["Verilog HDL"] },
        {
            name: "Operating Systems",
            skills: [
                "MS Windows (10",
                "Server 2012",
                "Phone",
                "Seven",
                "Vista",
                "XP",
                "9x",
                "CEx)",
                "MS-DOS",
                "Linux",
            ],
        },
        {
            name: "Virtualization",
            skills: ["IBM Cloud", "VMware", "Hyper-V", "Docker"],
        },
        {
            name: "Sciences",
            skills: [
                "Numerical analysis",
                "Calculus",
                "Computational intelligence",
                "Physics",
                "Chemistry",
            ],
        },
        {
            name: "Networking",
            skills: [
                "configuring and operating simple-routed LAN",
                "CISCO routers configuration",
                "Wireshark",
                "Packet Tracer",
            ],
        },
        {
            name: "Computer Maintenance",
            skills: ["Excellent Experience in PCs Hardware/Software maintenance"],
        },
        ],
    },
    certificates: [{
        date: "July 2023",
        name: "Western Certificate in University Teaching and Learning",
        institute: "Centre for Teaching and Learning at Western University.",
        score: "",
    }, {
        date: "DEC 2019",
        name: "IELTS General",
        institute: "British Council",
        score: "Total: 8.0, Reading:8.5 Writing:7.0 Listening:8.0 Speaking:7.5",
    },
    {
        date: "SEP 2016",
        name: "TOEFL IBT",
        institute: "ETS",
        score: "Total: 101, Reading:25 Writing:25 Listening:28 Speaking:23",
    },
    {
        date: "2015",
        name: "Microsoft Certified Professional",
        institute: "Microsoft",
        score: "",
    },
    {
        date: "2015",
        name: "Microsoft Certified Solution Developer: Web Applications.",
        institute: "Microsoft",
        score: "",
    },
    {
        date: "2015",
        name: "Microsoft Specialist: Programming in HTML5 with JavaScript and CSS3 Specialist.",
        institute: "Microsoft",
        score: "",
    },
    {
        date: "2010",
        name: "TRIZ Practitioner: TRIZ and xTRIZ-based Systematic Innovation for Technology and Engineering basic level",
        institute: "ICG training and consulting",
        score: "",
    },
    ],
    projects: {
        professional: [{
            date: "2017",
            name: "Hajj-related systems, HRM, Employee Attendance",
            company: "Saudi Ministry of defense/EJADA",
            country: "KSA",
            description: "Internal systems in Saudi Ministry of defense/EJADA serving thousands of users among nation area.",
        },
        {
            date: "2015",
            name: "Academic Portal",
            company: "JUST",
            country: "Jordan",
            description: "A~Z Customized Learning Management System built with state of the art web technologies serving 20,000+ JUST students.",
        },
        {
            date: "2011-2014",
            name: "JUST Online Exams",
            company: "JUST",
            country: "Jordan",
            description: "Two separate web application, an Administration for the online exams admin and delivery form the students, serving more than 200,000 exam session each semester.",
        },
        {
            date: "2014",
            name: "JUST Exam Maker",
            company: "JUST",
            country: "Jordan",
            description: "A windows application dedicated for instructor to help them creating their own online exams with pools management, questions and answers randomization, encryption and scheduling online sessions.",
        },
        {
            date: "2011-2015",
            name: "Memorandums System, Vacations System, Students Grading System, Instructors Electronic Promotions, JUST Job Forms, Rehab Newspaper Website",
            company: "JUST",
            country: "Jordan",
            description: "Internal systems for academic and administrative staff developed in JUST Computer Center.",
        },
        {
            date: "2013",
            name: "AraWeb.TV",
            company: "Araweb",
            country: "UAE",
            description: "A complete SDLC for a YouTube based web TV.",
        },
        {
            date: "2013",
            name: "IrbidGov",
            company: "CTS",
            country: "Jordan",
            description: "Photoshop Design and front end markup.",
        },
        {
            date: "2014",
            name: "DohaHouses, Car.sa",
            company: "Car.sa",
            country: "Qatar",
            description: "Photoshop Design and HTML markup.",
        },
        {
            date: "2011",
            name: "AIMs Carpet Cleaning, Bond Cleaning Brisbane, TheBugBandit Pest Control",
            company: "AIMs",
            country: "Australia",
            description: "Photoshop Design and markup.",
        },
        {
            date: "2013",
            name: "Projects Archiver",
            company: "Freelance",
            country: "KSA",
            description: "Online archiving system developed for students.",
        },
        {
            date: "2013",
            name: "Online Employment System",
            company: "Freelance",
            country: "KSA",
            description: "Online Recruitment website to be a connection between employers and candidates.",
        },
        {
            date: "2013",
            name: "Imam University IT Students Online Forums",
            company: "Freelance",
            country: "KSA",
            description: "Academic forums for IT faculty in Imam University.",
        },
        {
            date: "2012",
            name: "Online n-Depth Crawler",
            company: "Freelance",
            country: "KSA",
            description: "Basic Crawler and Google-like Search Engine.",
        },
        {
            date: "2012",
            name: "Photo Sharing Website",
            company: "Freelance",
            country: "KSA",
            description: "Basic Instagram-like photo management and sharing among friends, timeline, new photos feed.",
        },
        {
            date: "2012",
            name: "ArabWiki",
            company: "Freelance",
            country: "KSA",
            description: "Data Citation website.",
        },
        {
            date: "2013",
            name: "Applications Forms",
            company: "Freelance",
            country: "KSA",
            description: "Memorandums internal management system between university president, deans and department’s heads.",
        },
        {
            date: "2012",
            name: "IdeaBox",
            company: "Freelance",
            country: "KSA",
            description: "Connector service between idea’s owners, experienced consultants and investors.",
        },
        {
            date: "2013",
            name: "Official Website",
            company: "Freelance",
            country: "KSA",
            description: "Imam University Information Study Department Official Website.",
        },
        {
            date: "2012",
            name: "Integrated Students Services",
            company: "Freelance",
            country: "KSA",
            description: "Multiple services for master students and several related academic parts in university.",
        },
        {
            date: "2013",
            name: "Online Car Parking Reservation System",
            company: "Freelance",
            country: "KSA",
            description: "Online service for remote parking slots reservation integrated with local windows app for monitoring.",
        },
        {
            date: "2014",
            name: "Handbags",
            company: "Freelance",
            country: "Australia",
            description: "Basic eBay-like Ecommerce system for selling women handbags.",
        },
        {
            date: "2014",
            name: "Blogger Website",
            company: "Freelance",
            country: "Australia",
            description: "Blogging CMS with core features.",
        },
        {
            date: "2007",
            name: "Department of Plant Production website",
            company: "JUST",
            country: "Jordan",
            description: "Front end design and implementation.",
        },
        {
            date: "2005",
            name: "Jordan  Society  for  Scientific  Research website",
            company: "JSSR",
            country: "Jordan",
            description: "Design and implementation for the official website of the  Jordan  Society  for  Scientific  Research  (JSSR).",
        },
        ],

        academic: [{
            date: "2018",
            name: "A Glimpse on Consumer Behavior Change in Electric Power Consumption Using Socialization, Gamification and Visualization With Focus on Psychological Aspects",
            field: "Smart Systems",
            description: "Literature Review",
        },

        {
            date: "2018",
            name: "A Comparison Between MV* Design Patterns (MVC, MVP,MVVM) With An In-Depth N-Tier MVC Web Architecture",
            field: "Software Engineering for Cyber-Physical Systems",
            description: "Literature Review",
        },

        {
            date: "2017",
            name: "Experimental Evaluation Of Maximum-Flow Algorithms Using Four Different Augmenting Paths Searching Techniques Based on Ford-Fulkerson Algorithm",
            field: "Algorithms",
            description: "Quantitative evaluation",
        },

        {
            date: "2017",
            name: "The Titanic passengers survival prediction",
            field: "Data Science",
            description: "proposing different angles of visualization for the relations between features and by developing a predictive model using data science techniques such as Random Forests, Decision Trees and K-Nearest-Neighbors (K-NN) to predict whether each person survived or perished, based on the data available from that time",
        },

        {
            date: "2010-2013",
            name: "ART Algorithm AI data clustering, PlayFair Encryption Algorithm, A* Shortest Path Algorithm",
            field: "Algorithms",
            description: "Full implementation.",
        },

        {
            date: "2009",
            name: "Student Registration System",
            field: "Web Development",
            description: "Design and implementation of student registration system using PHP, HTML, CSS, and MySQL.",
        },

        {
            date: "2009",
            name: "Project Management System",
            field: "DB Design",
            description: "Design and implementation of a Project Management System using Oracle 10g , ER diagrams, forms and reports.",
        },

        {
            date: "2009",
            name: "Online Shopping System",
            field: "Web Development",
            description: "Implementation of an online shopping system based on registered users who can add or remove items to his cart, managed by system administrator have full access to the system, using ASP.NET and MS SQL server.",
        },

        {
            date: "2009",
            name: "Hardware",
            field: "Graduation Project",
            description: "Design and implementation of a pipelined high frequency single harmonic frequency detector based on bit reversal Fast Fourier Transform,IIR 4th orderellipticdigitalfilter,pipelineddigitalarithmeticMSI components and interpolated DFT algorithm for frequency measurement correction ,the implementation using Matlab, C++, C#.NET and mainly Verilog HDL synthesized in Synapticad.",
        },

        {
            date: "2009",
            name: "AES encryption",
            field: "Hardware",
            description: "Design and implementation of a pipelined AES encryption algorithm using Verilog HDL.",
        },

        {
            date: "2008",
            name: "IC Tester",
            field: "Hardware",
            description: "Building an IC Tester, Frequency Divider by writing Firmware assemblyprogramsdownloadedonMotorola68000-basedkitsusingMSHyper Terminal .",
        },

        {
            date: "2008",
            name: "Hardwired Computer System Kit",
            field: "Hardware",
            description: "Building a simple hardwired computer system kit using TTL components; 68008 Processor, RAM, EPROM, PTM, VMA and ACIA.	",
        },

        {
            date: "2008",
            name: "Consumers and Producers",
            field: "Multithreading",
            description: "Implementationofsynchronizationproblem (Multithreaded consumers and producers) using semaphores in C under Linux.",
        },

        {
            date: "2007",
            name: "RISC- Based Simulator,Assembler,and Linker/Loader",
            field: "Simulation",
            description: "DesignanddevelopmentofSimulator,Assembler,and Linker/Loader software package for a RISC-like ISA. The design is following object orienteddesignprinciplesusingUMLandRationalRose.Theimplementation language is C#.",
        },

        {
            date: "2007",
            name: "Arrival/Departure Scheduler",
            field: "Simulation",
            description: "Design and development of simulator for Arrival/Departure (process scheduling) systemsbased on queuing theory, using C#.NET.",
        },

        {
            date: "2007",
            name: "Web Server",
            field: "Networking",
            description: "Developing a simple WWW client, web server, and a proxy server using C#.NET socket programming.",
        },

        {
            date: "2007",
            name: "CDs library system",
            field: "DB Design",
            description: "Development and implementation for ausing OOP concepts,followingUMLdiagrams,implementedusingC#.NETwithADO.NET technology connected with MS Access DB",
        },

        {
            date: "2007",
            name: "Simulation",
            field: "Airport Runways Simulation",
            description: "Simulating the effect of increasing/decreasing the number of runwaysinairportstotheperformanceoflandinganddepartingplanesusing Simscript simulator",
        },

        {
            date: "2007",
            name: "Biomedical Equipments Management System",
            field: "WebDevelopment",
            description: "Designandimplementationofbiomedical equipments management system with two versions using ADO.NET under C#.NET as a windows application and with ASP.NET web application connecting to MS Access DB .",
        },

        {
            date: "2007",
            name: "Hospital System",
            field: "DB Design",
            description: "Design and implementation for patient/dependents history records used in a hospital system , implemented using C#.net with OOP/UML concepts with binary serialization.",
        },

        {
            date: "2006",
            name: "Low-pass digital filter",
            field: "Hardware",
            description: "Implementation of a low-pass elliptic 3rd order digital filter using Verilog HDL, Matlab and C++",
        },

        {
            date: "2005",
            name: "Cars Renting System",
            field: "DB Design",
            description: "Design of Cars Renting System from requirement elicitation and analysistousecase modelingandwritingdesigndocument.The implementation language being used was C#.net language and MS Access.",
        },
        ],
    },
    languages: [{
        name: "English",
        level: "excellent command",
    },
    {
        name: "Arabic",
        level: "native Speaker",
    },
    ],
    volunteer: [{
        date: "Jan 2021 - Present",
        location: "Rights and Responsibilities Awareness Initiative (RRAI), London, Canada.",
        role: "Information Technology Consultant",
    }, {
        date: "Aug 2023",
        location: "Computer Science Department, Western University",
        role: "Science Internship Report Judge",
    }, {
        date: "Jan 2021",
        location: "Computer Science Department, Western University",
        role: "Webmaster for UWORCS21",
    }, {
        date: "Feb 2021 - Apr 2021 ",
        location: "Faculty of Science, Western University",
        role: "Western National Scholarships Judge",
    }, {
        date: "Jan 2022 - Jan 2023",
        location: "Faculty of science, Western University.",
        role: "Co-leader of the Teaching & Learning group in the Strategic Planning Committee",
    }, {
        date: "2018-2020",
        location: "Western University Food Bank",
        role: "Coordinator and Graphic Designer",
    }
    ],
    conferences: [{
        date: "April 2021",
        name: "UWORCS 2021",
        role: "Presenter",
        city: "London, ON",
        country: "Canada",
    },
    {
        date: "June 2020",
        name: "IEEE WF-IoT2021",
        role: "Presenter",
        city: "Luisiana",
        country: "USA",
    },
    {
        date: "April 2019",
        name: "UWORCS 2019",
        role: "Attendant",
        city: "London, ON",
        country: "Canada",
    },
    {
        date: "2009",
        name: "the Technology Parade conference in Princess Sumaya University",
        role: "Participant",
        city: "Amman",
        country: "Jordan",
    },
    {
        date: "2007",
        name: "the 5th Investing in Technology Forum in Jordan under the Patronage of his majesty King Abdullah II bin Al Hussein.",
        role: "Participant",
        city: "Amman",
        country: "Jordan",
    },
    {
        date: "2002",
        name: "Jordanian conference for High  Schools mathematics computing",
        reason: "Presenter",
        city: "Zarqa",
        country: "Jordan",
    },
    ],
    training: {
        trainee: [
            {
                date: "2022",
                name: "The Advanced Teaching Program (ATP) ",
                city: "Centre for Teaching and Learning",
                country: "Western University",
                duration: "3 Full day training in course design strategies, active learning, authentic assessment of student learning, and maintaining a culture of respect and community in the classroom.",
            },
            {
                date: "2022",
                name: "The Teaching Mentor Program (TMP) ",
                city: "Centre for Teaching and Learning",
                country: "Western University",
                duration: "",
            }, {
                date: "2014",
                name: "Configuring and Administering Hyper-V in Windows Server 2012",
                city: "Amman",
                country: "Jordan",
                duration: "3 Full day training course 55021.",
            },
            {
                date: "2014",
                name: "Administering Microsoft SQL Server 2012 Databases",
                city: "Amman",
                country: "Jordan",
                duration: "5 Full day training course 10775",
            },
            {
                date: "2014",
                name: "Certified Software Tester – ISTQB Foundation Level.",
                city: "Amman",
                country: "Jordan",
                duration: "5 Full day training course.",
            },
            {
                date: "2014",
                name: "Microsoft System Center VMM",
                city: "Amman",
                country: "Jordan",
                duration: "3 Full day training course 55022.",
            },
            {
                date: "2012",
                name: "Windows Phone 7 Development",
                city: "Amman",
                country: "Jordan",
                duration: "2 Full day training.",
            },
            {
                date: "2011",
                name: "Wimba Create for Moodle",
                city: "Amman",
                country: "Jordan",
                duration: "2 Full day training course.",
            },
            {
                date: "2011",
                name: "Echo360 lecture capture solutions",
                city: "Amman",
                country: "Jordan",
                duration: "3 Full day training course.",
            },
            {
                date: "2011",
                name: "IBM CloudBurst over VMware",
                city: "Amman",
                country: "Jordan",
                duration: "14 Full day training course.",
            },
            {
                date: "2011",
                name: "Video/Audio Editing for eLearning purposes",
                city: "Amman",
                country: "Jordan",
                duration: "5 Full day training course.",
            },
        ],
        trainer: [{
            date: "2014",
            name: "web development using Asp.net/C#, HTML5, CSS3, jQuery and database using SQL server 2012 to build fully functional wiki-like content management system.",
            city: "Irbid",
            country: "Jordan",
            duration: "6 Months day to day training for 12 undergraduate students",
        },
        {
            date: "2012",
            name: "using Adobe Photoshop cs5 featuring dealing with layers, web mockups design, masking and photo manipulation",
            city: "Irbid",
            country: "Jordan",
            duration: "5 full day training for 15 engineers/programmers.",
        },
        ],
    },
    tpc: [
        {
            name: "IEEE Access",
            date: "2023"
        },
        {
            name: "IEEE Internet of Things Journal",
            date: "2023"
        },
        {
            name: "IEEE Transactions on Industrial Informatics",
            date: "2022"
        },
        {
            name: "IEEE Canadian Journal for Electrical and Computer Engineering CJECE ",
            date: "2022"
        },
        {
            name: "IEEE Internet of Things Journal",
            date: "2021"
        },
        {
            name: "CNSM2020",
            city: "Izmir",
            country: "Turkey",
            date: "2020",
            url: "http://www.cnsm-conf.org/2020/"
        },
        {
            name: "WiMOB2020",
            city: "Zoom",
            country: "Virtual",
            date: "2020",
            url: "https://wimob.org/wimob2020/"
        },
        {
            name: "Vehicular Communications Journal",
            date: "2020",
            url: "https://www.journals.elsevier.com/vehicular-communications"
        },
        {
            name: "IEEE URUCON",
            date: "2021"
        }
    ],
    memberships: [
        "IEEE Canada",
        "Western Alumni",
        "Public Service Alliance of Canada (PSAC)",
        "Jordan Engineers Association (JEA)",
        "Saudi Council for Engineers (SCE)",
    ],
    interests: [
        "Learning",
        "Teaching",
        "Math/Logic Puzzle Solving",
        "Home Cooking",
    ],
    references: [{
        name: "Prof. Hanan Lutfiyya",
        company: "University of Western Ontario",
        position: "Professor",
        email: "hlutfiyy@uwo.ca",
        website: "www.csd.uwo.ca/faculty/hanan/",
    },
    {
        name: "Dr. Anwar Haque",
        company: "University of Western Ontario",
        position: "Associate Professor",
        email: "ahaque32@uwo.ca",
        website: "csd.uwo.ca/~ahaque32",
    },{
        name: "Dr. Zubair Md Fadlullah",
        company: "University of Western Ontario",
        position: "Associate Professor",
        email: "zubair.fadlullah@uwo.ca",
        website: "www.zfadlullah.org",
    }
    ,{
        name: "Dr. Daniel Servos",
        company: "University of Western Ontario",
        position: "Assistant Professot",
        email: "dservos5@uwo.ca",
        website: "danielservos.ca",
    },{
        name: "Bryan Sarlo",
        company: "University of Western Ontario",
        position: "Undergraduate Chair",
        email: "bsarlo@uwo.ca",
        website: "csd.uwo.ca/people/faculty/bios/sarlo.html",
    },
    // {
    //     name: "Prof.Omar Al-Jarrah",
    //     company: "Jordan University of Science and Technology",
    //     position: "Former President",
    //     email: "aljarrah@just.edu.jo",
    //     website: "www.just.edu.jo/~aljarrah",
    // },
    // {
    //     name: "Dr.Amer Magableh",
    //     company: "Jordan University of Science and Technology",
    //     position: "Computer and Information Center Former Director",
    //     email: "ammagableh@just.edu.jo",
    //     website: "http://www.just.edu.jo/~ammagableh",
    // },
    // {
    //     name: "Dr.Mohammed Shatnawi",
    //     company: "Jordan University of Science and Technology",
    //     position: "Computer and Information Center Former Vise Director",
    //     email: "mshatnawi@just.edu.jo",
    //     website: "http://www.just.edu.jo/~mshatnawi",
    // },
    // {
    //     name: "Nabil Bkairat",
    //     company: "Ejada Systems",
    //     position: "COO",
    //     email: "nalbkairat@ejada.com",
    //     phone: "+966-50-547-6180",
    //     website: "http://www.ejada.com",
    // },
    ],
};
